import Verso
import VersoManual
import VersoBlueprint
import VersoBlueprint.Commands.Graph
import VersoBlueprint.Commands.Summary
import UpstreamingBlueprint.Chapters.Graph

open Verso.Genre
open Verso.Genre.Manual
open Informal

#doc (Manual) "MathlibStaging upstreaming dashboard" =>

This dashboard visualises the staging-internal dependency graph of the
`MathlibStaging` library, to help decide what can be upstreamed to mathlib next.
The graph is generated by `lake exe upstream viz --decls --format verso` in the
main repository.

{include 0 UpstreamingBlueprint.Chapters.Graph}

{blueprint_graph}
{blueprint_summary}
